name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push images
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          for service in emailsender frontend scheduler tracker; do
            echo "Building $service..."
            docker buildx build \
              --push \
              --platform linux/amd64 \
              --tag ${DOCKERHUB_USERNAME}/$service:${SHORT_SHA} \
              --file $service/Dockerfile \
              --build-arg BUILDKIT_INLINE_CACHE=1 \
              .
          done